spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;
  jpa:
    generate-ddl: off
    database: h2
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql